services:
  python-cron-job-runner:
    build: .
    image: python-cron-job-runner:latest
    container_name: python-cron-job-runner
    volumes:
      - ./log:/log
      - ./scripts:/scripts
      - proj-venv:/proj-venv
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

volumes:
  proj-venv:
